#!/bin/bash
my_name=$(basename -- "$0")
if [ $# -lt 2 ]; then
  echo "Usage: $my_name site_env password"
  echo "Purpose: Create a database accessible to the databasename at localhost using password"
  echo "Eg: $my_name hkern0_local myspecialpassword"
  exit 1
fi
sudo mysql -e "CREATE DATABASE IF NOT EXISTS \`$1\`;GRANT ALL PRIVILEGES ON \`$1\`.* TO '$1'@'localhost' IDENTIFIED BY '$2';"
