#!/bin/bash
# db_init_from_backup hkern0_local i9mG1C /srv/www/wd/.site-backups/hkern0_live_2021-04-02T16-00-31_db
db_init_from_backup hkern0_stage Jz8Pa7 /srv/www/wd/.site-backups/hkern0_live_2021-04-02T16-00-31_db
db_init_from_backup yad7_local y9TKc5 /srv/www/wd/.site-backups/hkern0_live_2021-04-02T16-00-31_db
db_init_from_backup yad7_stage rGN1zw /srv/www/wd/.site-backups/hkern0_live_2021-04-02T16-00-31_db
db_init_from_backup jp_local n1kW3m /srv/www/jp/.site-backups/jp_local_2019-12-29T09-22-14_db
db_init_from_backup jp_stage oYJ8fw /srv/www/jp/.site-backups/jp_local_2019-12-29T09-22-14_db
# db_init_from_backup pbwe_local iBXN2M
# db_init_from_backup pbwe_stage TFC3pC
db_init_from_backup ab_local M4v3L2 /srv/www/wd/.site-backups/ab_local_2021-01-31T12-05-16_db
db_init_from_backup ab_stage /srv/www/wd/.site-backups/Jc4KQW ab_local_2021-01-31T12-05-16_db
db_init_from_backup abc_local Qw4ZAZ /srv/www/abc/.site-backups/abc_neo_2021-03-22T13-28-17_db
db_init_from_backup abc_stage JKD1j0 /srv/www/abc/.site-backups/abc_neo_2021-03-22T13-28-17_db
db_init_from_backup abix_local /srv/www/wd/.site-backups/k35Dw9 abix_live_2021-04-04T15-11-28_db
db_init_from_backup abix_stage /srv/www/wd/.site-backups/mm4zHe abix_live_2021-04-04T15-11-28_db
